[PHP]
date.timezone=Asia/Makassar
memory_limit=512M
max_execution_time=300
max_input_time=300
post_max_size=150M
upload_max_filesize=150M
max_file_uploads=50
max_input_vars=10000
variables_order=EGPCS
realpath_cache_size=4096K
realpath_cache_ttl=600

[Session]
session.gc_maxlifetime=7200

[opcache]
opcache.enable=1
opcache.enable_cli=1
