[PHP]
date.timezone=Asia/Makassar
memory_limit=512M
max_execution_time=300
max_input_time=300
post_max_size=100M
upload_max_filesize=100M
variables_order=EGPCS
realpath_cache_size=4096K
realpath_cache_ttl=600

[Session]
session.gc_maxlifetime=7200

[opcache]
opcache.enable=1
opcache.enable_cli=1
